version: '3.8'

services:
    database:
        image: postgres:17.2-alpine
        ports:
            - 5432:5432
        volumes:
            - database:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=rootroot
            - POSTGRES_USER=rootroot
            - POSTGRES_DB=try_k6

volumes:
    database:

networks:
    app:
